# Generated by Django 5.2.6 on 2025-12-16 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
