# Generated by Django 5.2.6 on 2025-12-16 06:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_tenant'),
        ('sales', '0004_sale_tenant_saleitem_tenant'),
        ('tenants', '0003_subscription_paymenthistory_usagetracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyPointsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points_per_rupee', models.DecimalField(decimal_places=4, default=Decimal('1.00'), help_text='Number of points earned per rupee spent (e.g., 1.0 = 1 point per ₹1)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('point_value_in_rupees', models.DecimalField(decimal_places=4, default=Decimal('0.10'), help_text='Value of 1 point in rupees (e.g., 0.10 = 1 point = ₹0.10)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('maximum_redeem_percentage', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Maximum percentage of bill amount that can be redeemed using points (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('minimum_purchase_amount', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Minimum purchase amount required to earn/redeem points', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('minimum_points_to_redeem', models.IntegerField(default=100, help_text='Minimum points required to redeem', validators=[django.core.validators.MinValueValidator(1)])),
                ('points_expiration_days', models.IntegerField(default=365, help_text='Number of days after which points expire (0 = no expiration)', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable loyalty points program')),
                ('allow_partial_redemption', models.BooleanField(default=True, help_text='Allow customers to redeem partial points')),
                ('round_points', models.BooleanField(default=True, help_text='Round points to nearest integer when calculating')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Loyalty Points Configuration',
                'verbose_name_plural': 'Loyalty Points Configurations',
                'ordering': ['-created_at'],
                'unique_together': {('tenant',)},
            },
        ),
        migrations.CreateModel(
            name='LoyaltyPointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('transaction_type', models.CharField(choices=[('earned', 'Points Earned'), ('redeemed', 'Points Redeemed'), ('expired', 'Points Expired'), ('adjusted', 'Points Adjusted'), ('refunded', 'Points Refunded')], help_text='Type of loyalty points transaction', max_length=20)),
                ('points', models.IntegerField(help_text='Number of points (positive for earned, negative for redeemed)')),
                ('points_balance_after', models.IntegerField(default=0, help_text='Customer points balance after this transaction')),
                ('purchase_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Purchase amount that generated this transaction', max_digits=10, null=True)),
                ('redemption_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount redeemed using points', max_digits=10, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Date when these points expire (for earned points)', null=True)),
                ('is_expired', models.BooleanField(default=False, help_text='Whether these points have expired')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', help_text='Transaction status', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='External reference number (e.g., invoice number)', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format')),
                ('customer', models.ForeignKey(help_text='Customer associated with this transaction', on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='customer.customer')),
                ('sale', models.ForeignKey(blank=True, help_text='Sale transaction associated with this points transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='sales.sale')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Loyalty Points Transaction',
                'verbose_name_plural': 'Loyalty Points Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'transaction_type'], name='customer_lo_custome_cfb986_idx'), models.Index(fields=['customer', 'created_at'], name='customer_lo_custome_3e5d2a_idx'), models.Index(fields=['expires_at', 'is_expired'], name='customer_lo_expires_0b4f33_idx'), models.Index(fields=['sale'], name='customer_lo_sale_id_21dfc7_idx')],
            },
        ),
    ]
