# Generated by Django 5.2.6 on 2025-11-23 16:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('plan_type', models.CharField(choices=[('trial', 'Free Trial'), ('basic', 'Basic Plan'), ('professional', 'Professional Plan'), ('enterprise', 'Enterprise Plan')], default='trial', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, help_text='Monthly subscription price', max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, help_text='Yearly subscription price (Usually with discount)', max_digits=10)),
                ('max_users', models.IntegerField(default=1, help_text='Maximum User/Staff allowed')),
                ('max_products', models.IntegerField(default=100, help_text='Maximum products in inventory')),
                ('max_transactions_per_month', models.IntegerField(default=100, help_text='Maximum sales transactions per month')),
                ('max_locations', models.IntegerField(default=1, help_text='Maximum store locations')),
                ('has_analytics', models.BooleanField(default=False)),
                ('has_advanced_reports', models.BooleanField(default=False)),
                ('has_multi_location', models.BooleanField(default=False)),
                ('has_api_access', models.BooleanField(default=False)),
                ('has_priority_support', models.BooleanField(default=False)),
                ('has_custom_branding', models.BooleanField(default=False)),
                ('has_inventory_alerts', models.BooleanField(default=True)),
                ('has_customer_management', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True, help_text='Show in pricing page')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['sort_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(help_text='Legal business/company name', max_length=200)),
                ('subdomain', models.SlugField(max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='Subdomain must be lowercase letters, numbers, and hypens only', regex='^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$')])),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='India', max_length=100)),
                ('gstin', models.CharField(blank=True, help_text='GST Identification Number (India)', max_length=50)),
                ('subscription_status', models.CharField(choices=[('trial', 'Trial Period'), ('active', 'Active'), ('past_due', 'Past Due'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='trial', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trial_starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_starts_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_ends_at', models.DateTimeField(blank=True, null=True)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Asis/Kolkata', max_length=50)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('custom_features', models.JSONField(blank=True, default=dict, help_text='Custom feature flags that override plan defaults')),
                ('current_users_count', models.IntegerField(default=0)),
                ('current_product_count', models.IntegerField(default=0)),
                ('current_month_transactions', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='tenants.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subdomain'], name='tenants_ten_subdoma_6c6a7a_idx'), models.Index(fields=['owner_email'], name='tenants_ten_owner_e_da4089_idx'), models.Index(fields=['subscription_status', 'is_active'], name='tenants_ten_subscri_c50aef_idx')],
            },
        ),
    ]
