# Generated by Django 5.2.6 on 2025-12-16 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_subscription_paymenthistory_usagetracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='billing_cycle',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='tenants.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='subscription_status',
            field=models.CharField(blank=True, choices=[('trial', 'Trial Period'), ('active', 'Active'), ('past_due', 'Past Due'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='trial', max_length=20, null=True),
        ),
    ]
