# Generated by Django 5.2.6 on 2025-11-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='product_name',
            new_name='product',
        ),
    ]
