# Generated by Django 5.2.6 on 2025-11-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_product_name_saleitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='customer_name',
            new_name='customer',
        ),
    ]
