# Generated by Django 5.2.6 on 2025-11-24 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_customer_name_sale_customer'),
        ('tenants', '0002_tenantuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='tenant',
            field=models.ForeignKey(default='1152d947-9ab6-4c58-b6fd-7e34ebf8585d', help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitem',
            name='tenant',
            field=models.ForeignKey(default='1152d947-9ab6-4c58-b6fd-7e34ebf8585d', help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
            preserve_default=False,
        ),
    ]
